# Generated by Django 2.2.7 on 2019-11-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='ContactMessage',
        ),
    ]
